### PR TITLE
refactor SkillGUI class to import from ovos_utils

### PR DESCRIPTION
**Pull request by JarbasAl**
there was a bunch of duplicated code and the API was starting to get out of sync with ovos_utils getting new features such as notifications support

### CODE REVIEW

**Comment by AIIX** [comment]
This will make GUI completely ovos-utils dependent and also means gui skills will also now indirectly become ovos utils dependent, i don't see how that is a good thing, and why it all needs to be moved outside core, if anything ovos-utils gui changes should be moved here instead for better sync than live outside core

**Comment by AIIX** [comment]
request to avoid merging this till its better tested, seems it removes a lot of GUI specific code

**Comment by JarbasAl** [comment]
> This will make GUI completely ovos-utils dependent and also means gui skills will also now indirectly become ovos utils dependent, i don't see how that is a good thing, and why it all needs to be moved outside core, if anything ovos-utils gui changes should be moved here instead for better sync than live outside core

you added the new notification utils there because they are used in PHAL plugins etc, in ovos things other than skills can have a GUI interface. 

there was no code removed here, all code you see deleted is the exact same function in ovos_utils,

ovos_utils is already a dependency of ovos-core. MycroftSkill class will remain working exactly the same, skills will not be tied to ovos_utils at all since they import from mycroft module. this doesnt even add a new dependency

also we cant really extend this class with new public methods just like skills, because then if a skill uses the new methods it wont run in mycroft-core. moving the changes from ovos-utils here is exactly the wrong thing to do since it breaks backwards compat and blocks plugins from having a GUI

**Comment by AIIX** [comment]
> > This will make GUI completely ovos-utils dependent and also means gui skills will also now indirectly become ovos utils dependent, i don't see how that is a good thing, and why it all needs to be moved outside core, if anything ovos-utils gui changes should be moved here instead for better sync than live outside core
> 
> you added the new notification utils there because they are used in PHAL plugins etc, in ovos things other than skills can have a GUI interface. 
> 
> there was no code removed here, all code you see deleted is the exact same function in ovos_utils,
> 
> ovos_utils is already a dependency of ovos-core. MycroftSkill class will remain working exactly the same, skills will not be tied to ovos_utils at all since they import from mycroft module. this doesnt even add a new dependency
> 
> also we cant really extend this class with new public methods just like skills, because then if a skill uses the new methods it wont run in mycroft-core. moving the changes from ovos-utils here is exactly the wrong thing to do since it breaks backwards compat and blocks plugins from having a GUI

This is still untested, and I would like to test this PR running on device with everything before I can say nothing breaks in GUI with this change

**Review by builderjer — APPROVED** [review]
I've been testing, and have no seen issues

**Review by AIIX — APPROVED** [review]

**Pull request merged**
