### PR TITLE
refactor/padatious_samples

### PR DESCRIPTION
**Pull request by JarbasAl**
padatious accepted a file path in the bus message registering intents, this causes issues when using skills standalone via ovos-workshop SkillContainer, the file is not assured to exist in ovos-core

this adds support for messages to send the samples directly, a companion PR in ovos workshop will update the emitted message

backwards compat is maintained with no version sync needed

### CODE REVIEW

**Comment by goldyfruit** [comment]
Even with this PR, I'm still not able to have the personal skill working.

From core logs:
```
2023-04-23 11:01:12.420 - skills - mycroft.skills.intent_service:_normalize_all_utterances:61 - DEBUG - Utterances: [('who made you',)]
2023-04-23 11:01:12.496 - skills - mycroft.skills.intent_services.padatious_service:_match_level:87 - DEBUG - Padatious Matching confidence > 0.95
2023-04-23 11:01:12.694 - skills - mycroft.skills.intent_services.commonqa_service:handle_question:119 - INFO - Searching for who made you
2023-04-23 11:01:12.815 - skills - mycroft.skills.intent_services.commonqa_service:_query_timeout:174 - INFO - Timeout occurred check responses
2023-04-23 11:01:12.896 - skills - mycroft.skills.intent_services.commonqa_service:_query_timeout:168 - WARNING - got a common query response outside search window
2023-04-23 11:01:12.908 - skills - ovos_workshop.skills.fallback:handler:72 - DEBUG - Checking fallbacks in range 0 - 5
```

From the personal skill log:
```
2023-04-23 13:49:50.754 - OVOS - ovos_config.models:load_local:105 - DEBUG - Configuration /usr/lib/python3.11/site-packages/mycroft/configuration/mycroft.conf loaded
2023-04-23 13:49:50.870 - OVOS - ovos_config.models:load_local:111 - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not defined, skipping
2023-04-23 13:49:51.041 - OVOS - ovos_config.models:load_local:105 - DEBUG - Configuration /home/ovos/.config/mycroft/web_cache.json loaded
2023-04-23 13:49:51.516 - OVOS - ovos_config.models:load_local:105 - DEBUG - Configuration /home/ovos/.config/mycroft/mycroft.conf loaded
2023-04-23 13:49:51.664 - OVOS - ovos_config.models:load_local:111 - DEBUG - Configuration '/etc/xdg/mycroft/mycroft.conf' not defined, skipping
2023-04-23 13:49:51.749 - OVOS - ovos_config.models:load_local:111 - DEBUG - Configuration '/home/ovos/.mycroft/mycroft.conf' not defined, skipping
2023-04-23 13:49:54.174 - OVOS - ovos_plugin_manager.ocp:load:33 - INFO - Loaded OCP plugin: ovos-ocp-files-plugin
2023-04-23 13:49:55.388 - OVOS - ovos_utils.configuration:get_xdg_config_save_path:141 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-04-23 13:49:56.474 - OVOS - ovos_utils.configuration:get_xdg_base:76 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-04-23 13:49:57.678 - OVOS - ovos_bus_client.conf:load_message_bus_config:19 - INFO - Loading message bus configs
2023-04-23 13:49:57.695 - OVOS - ovos_bus_client.client.client:on_open:85 - INFO - Connected
2023-04-23 13:49:57.699 - OVOS - ovos_workshop.skill_launcher:_connect_to_core:499 - DEBUG - checking skills service status
2023-04-23 13:49:57.706 - OVOS - ovos_bus_client.session:reset_default_session:175 - INFO - New Default Session Start: 6066f780-aac7-406c-b182-f4c2aaeba2c1
2023-04-23 13:50:00.710 - OVOS - ovos_workshop.skill_launcher:_connect_to_core:507 - WARNING - ovos-core does not seem to be running
2023-04-23 13:50:15.142 - OVOS - ovos_workshop.skill_launcher:load_skill:516 - INFO - launching skill
2023-04-23 13:50:15.441 - OVOS - ovos_workshop.skill_launcher:load:465 - INFO - ATTEMPTING TO LOAD PLUGIN SKILL: ovos-skill-personal.OpenVoiceOS
2023-04-23 13:50:15.452 - ovos-skill-personal.OpenVoiceOS - DEBUG - initializing skill settings for ovos-skill-personal.OpenVoiceOS
2023-04-23 13:50:15.517 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: skill.converse.ping
2023-04-23 13:50:15.555 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: skill.converse.request
2023-04-23 13:50:15.572 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS.activate
2023-04-23 13:50:15.603 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS.deactivate
2023-04-23 13:50:15.618 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: intent.service.skills.deactivated
2023-04-23 13:50:15.630 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: intent.service.skills.activated
2023-04-23 13:50:15.662 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skill.enable_intent
2023-04-23 13:50:15.670 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skill.disable_intent
2023-04-23 13:50:15.683 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skill.set_cross_context
2023-04-23 13:50:15.694 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skill.remove_cross_context
2023-04-23 13:50:15.728 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.changed
2023-04-23 13:50:15.744 - OVOS - ovos_utils.skills.audioservice:__init__:228 - WARNING - AudioServiceInterface has been deprecated, compatibility layer in use
please move to OCPInterface
2023-04-23 13:50:15.749 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS.set
2023-04-23 13:50:15.777 - OVOS - ovos_utils.configuration:get_xdg_config_save_path:141 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-04-23 13:50:15.831 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.update
2023-04-23 13:50:15.837 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.download
2023-04-23 13:50:15.841 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.upload
2023-04-23 13:50:15.862 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.upload.meta
2023-04-23 13:50:15.866 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.paired
2023-04-23 13:50:15.905 - OVOS - mycroft.deprecated.skills.settings:__init__:99 - WARNING - skill_name is deprecated! use skill_id instead
2023-04-23 13:50:16.054 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:DoYouRhyme.intent
2023-04-23 13:50:16.112 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhereWereYouBorn.intent
2023-04-23 13:50:16.161 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhoMadeYou.intent
2023-04-23 13:50:16.223 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:DoYouDream.intent
2023-04-23 13:50:16.291 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhoAreYou.intent
2023-04-23 13:50:16.360 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhatAreYou.intent
2023-04-23 13:50:16.441 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhenWereYouBorn.intent
2023-04-23 13:50:16.444 - OVOS - ovos_workshop.skill_launcher:_create_skill_instance:428 - WARNING - Deprecated skill signature! Skill class should be imported from `ovos_workshop.skills`
2023-04-23 13:50:16.455 - OVOS - ovos_workshop.skill_launcher:_communicate_load_status:449 - INFO - Skill ovos-skill-personal.OpenVoiceOS loaded successfully
2023-04-23 14:58:19.147 - OVOS - ovos_config.models:load_local:105 - DEBUG - Configuration /usr/lib/python3.11/site-packages/mycroft/configuration/mycroft.conf loaded
2023-04-23 14:58:19.186 - OVOS - ovos_config.models:load_local:111 - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not defined, skipping
2023-04-23 14:58:19.224 - OVOS - ovos_config.models:load_local:105 - DEBUG - Configuration /home/ovos/.config/mycroft/web_cache.json loaded
2023-04-23 14:58:19.269 - OVOS - ovos_config.models:load_local:105 - DEBUG - Configuration /home/ovos/.config/mycroft/mycroft.conf loaded
2023-04-23 14:58:19.305 - OVOS - ovos_config.models:load_local:111 - DEBUG - Configuration '/etc/xdg/mycroft/mycroft.conf' not defined, skipping
2023-04-23 14:58:19.340 - OVOS - ovos_config.models:load_local:111 - DEBUG - Configuration '/home/ovos/.mycroft/mycroft.conf' not defined, skipping
2023-04-23 14:58:20.781 - OVOS - ovos_plugin_manager.ocp:load:33 - INFO - Loaded OCP plugin: ovos-ocp-files-plugin
2023-04-23 14:58:21.132 - OVOS - ovos_utils.configuration:get_xdg_config_save_path:141 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-04-23 14:58:21.395 - OVOS - ovos_utils.configuration:get_xdg_base:76 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-04-23 14:58:21.751 - OVOS - ovos_bus_client.conf:load_message_bus_config:19 - INFO - Loading message bus configs
2023-04-23 14:58:21.759 - OVOS - ovos_bus_client.client.client:on_open:85 - INFO - Connected
2023-04-23 14:58:21.760 - OVOS - ovos_workshop.skill_launcher:_connect_to_core:499 - DEBUG - checking skills service status
2023-04-23 14:58:21.764 - OVOS - ovos_bus_client.session:reset_default_session:175 - INFO - New Default Session Start: dfa5061e-fbaf-466b-8521-633996f06807
2023-04-23 14:58:21.818 - OVOS - ovos_workshop.skill_launcher:_connect_to_core:504 - INFO - connected to core
2023-04-23 14:58:21.820 - OVOS - ovos_workshop.skill_launcher:load_skill:516 - INFO - launching skill
2023-04-23 14:58:21.909 - OVOS - ovos_workshop.skill_launcher:load:465 - INFO - ATTEMPTING TO LOAD PLUGIN SKILL: ovos-skill-personal.OpenVoiceOS
2023-04-23 14:58:21.910 - ovos-skill-personal.OpenVoiceOS - DEBUG - initializing skill settings for ovos-skill-personal.OpenVoiceOS
2023-04-23 14:58:21.919 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: skill.converse.ping
2023-04-23 14:58:21.922 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: skill.converse.request
2023-04-23 14:58:21.925 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS.activate
2023-04-23 14:58:21.928 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS.deactivate
2023-04-23 14:58:21.931 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: intent.service.skills.deactivated
2023-04-23 14:58:21.934 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: intent.service.skills.activated
2023-04-23 14:58:21.938 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skill.enable_intent
2023-04-23 14:58:21.941 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skill.disable_intent
2023-04-23 14:58:21.945 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skill.set_cross_context
2023-04-23 14:58:21.949 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skill.remove_cross_context
2023-04-23 14:58:21.952 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.changed
2023-04-23 14:58:21.957 - OVOS - ovos_utils.skills.audioservice:__init__:228 - WARNING - AudioServiceInterface has been deprecated, compatibility layer in use
please move to OCPInterface
2023-04-23 14:58:21.960 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS.set
2023-04-23 14:58:21.965 - OVOS - ovos_utils.configuration:get_xdg_config_save_path:141 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-04-23 14:58:21.970 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.update
2023-04-23 14:58:21.973 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.download
2023-04-23 14:58:21.976 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.upload
2023-04-23 14:58:21.979 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.skills.settings.upload.meta
2023-04-23 14:58:21.982 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: mycroft.paired
2023-04-23 14:58:21.995 - OVOS - mycroft.deprecated.skills.settings:__init__:99 - WARNING - skill_name is deprecated! use skill_id instead
2023-04-23 14:58:22.037 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhereWereYouBorn.intent
2023-04-23 14:58:22.055 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhatAreYou.intent
2023-04-23 14:58:22.085 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhoMadeYou.intent
2023-04-23 14:58:22.108 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:DoYouDream.intent
2023-04-23 14:58:22.125 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhenWereYouBorn.intent
2023-04-23 14:58:22.147 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:WhoAreYou.intent
2023-04-23 14:58:22.167 - OVOS - ovos_utils.messagebus:add:645 - DEBUG - Added event: ovos-skill-personal.OpenVoiceOS:DoYouRhyme.intent
2023-04-23 14:58:22.172 - OVOS - ovos_workshop.skill_launcher:_create_skill_instance:428 - WARNING - Deprecated skill signature! Skill class should be imported from `ovos_workshop.skills`
2023-04-23 14:58:22.185 - OVOS - ovos_workshop.skill_launcher:_communicate_load_status:449 - INFO - Skill ovos-skill-personal.OpenVoiceOS loaded successfully
```

**Comment by goldyfruit** [comment]
Some intents as well are not working, for example: "what is the temperature" works but "Do I need an umbrella" does not.

**Comment by JarbasAl** [comment]
also needs https://github.com/OpenVoiceOS/OVOS-workshop/pull/66

**Comment by goldyfruit** [comment]
> also needs [OpenVoiceOS/OVOS-workshop#66](https://github.com/OpenVoiceOS/OVOS-workshop/pull/66)

Does it needs to run with core or with the skill?

**Comment by JarbasAl** [comment]
ovos_workshop needs to be updated in the skill, this will emit the new optional data with all samples on the bus instead of filepath

ovos-core needs to also be updated to actually consume those samples

**Comment by goldyfruit** [comment]
> ovos_workshop needs to be updated in the skill, this will emit the new optional data with all samples on the bus instead of filepath
> 
> ovos-core needs to also be updated to actually consume those samples
When install the  PR 66 into the skill container I got this.

```
2023-04-23 21:14:03.529 - OVOS - ovos_workshop.skills.auto_translatable:<module>:11 - ERROR - No module named 'ovos_utils.lang.translate'
Traceback (most recent call last):
  File "/home/ovos/.local/lib/python3.11/site-packages/ovos_workshop/skills/auto_translatable.py", line 7, in <module>
    from ovos_utils.lang.translate import detect_lang, translate_text
ModuleNotFoundError: No module named 'ovos_utils.lang.translate'
Traceback (most recent call last):
  File "/usr/bin/ovos-skill-launcher", line 5, in <module>
    from ovos_workshop.skill_launcher import _launch_script
  File "/home/ovos/.local/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 25, in <module>
    from ovos_workshop.skills.fallback import FallbackSkill
  File "/home/ovos/.local/lib/python3.11/site-packages/ovos_workshop/skills/fallback.py", line 38, in <module>
    class FallbackSkill(OVOSSkill, metaclass=_MutableFallback):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by JarbasAl** [comment]
> > ovos_workshop needs to be updated in the skill, this will emit the new optional data with all samples on the bus instead of filepath
> > ovos-core needs to also be updated to actually consume those samples
> 
> When I install the PR 66 into the skill container I got this.
> 
> ```
> 2023-04-23 21:14:03.529 - OVOS - ovos_workshop.skills.auto_translatable:<module>:11 - ERROR - No module named 'ovos_utils.lang.translate'
> Traceback (most recent call last):
>   File "/home/ovos/.local/lib/python3.11/site-packages/ovos_workshop/skills/auto_translatable.py", line 7, in <module>
>     from ovos_utils.lang.translate import detect_lang, translate_text
> ModuleNotFoundError: No module named 'ovos_utils.lang.translate'
> Traceback (most recent call last):
>   File "/usr/bin/ovos-skill-launcher", line 5, in <module>
>     from ovos_workshop.skill_launcher import _launch_script
>   File "/home/ovos/.local/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 25, in <module>
>     from ovos_workshop.skills.fallback import FallbackSkill
>   File "/home/ovos/.local/lib/python3.11/site-packages/ovos_workshop/skills/fallback.py", line 38, in <module>
>     class FallbackSkill(OVOSSkill, metaclass=_MutableFallback):
> TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
> ```

fixed now https://github.com/OpenVoiceOS/OVOS-workshop/pull/66

**Pull request merged**
